### ISSUE TITLE
OCS_DBI_PRINT_ERROR is missing

### ISSUE THREAD

**Issue by wsams** [OCSInventory-NG/OCSInventory-Docker-Image#114]
I'm not sure where to file this issue as it crosses over into the Helm chart and maybe the primary project. It looks like the value for `OCS_OPT_DBI_PRINT_ERROR`,

https://github.com/OCSInventory-NG/OCSInventory-Docker-Image/blob/master/2.11/conf/ocsinventory-server.conf#L77

is now being set via an environment variable `OCS_DBI_PRINT_ERROR` in the latest image 2.12.1.

In the Helm chart I added,

```
          env:
          - name: "OCS_DBI_PRINT_ERROR"
            # This value is replaced in /etc/apache/conf-available/z-ocsinventory-server.conf
            value: "0"
```

but maybe this needs to be documented somewhere, or added to the chart and main repo?

I can provide more details or clarifications if needed. Thanks
